# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
MenuItem.create(item: 'Avocado Egg Rolls', category: 'Shareable Appetizers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:10.75, description:'A blend of avocados, cream cheese, sun-dried tomatoes, red onions, cilantro, pine nuts, chipotle peppers and spices. Served with a sweet tamarind sauce.')
MenuItem.create(item: 'Shrimp Lettuce Wraps', category: 'Shareable Appetizers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:11.25, description:'Spicy Thai glazed shrimp, Napa cabbage, cilantro, carrots, red onions, minty mango salsa and toasted coconut.')
MenuItem.create(item: 'Ahi Poke', category: 'Shareable Appetizers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:10.50, description:'Chopped sashimi grade ahi tuna and green and yellow onions marinated in our signature poke sauce. Topped with diced avocados and served with crisp wonton chips.')
MenuItem.create(item: 'Crispy Calamari', category: 'Shareable Appetizers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:10.25, description:'With spicy marinara and lemon garlic aioli.')
MenuItem.create(item: 'Mozzarella Sticks', category: 'Shareable Appetizers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:7.95, description:'Coated with a crisp garlic butter breading, sprinkled with Parmesan cheese and served with marinara sauce.')

MenuItem.create(item: 'Pepperoni Extreme', category: 'Pizza', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:19.75, description:'Big, bold flavor featuring zesty pizza sauce, BJ’s signature five cheese blend and triple pepperoni sliced, diced and julienned.')
MenuItem.create(item: 'BJs Favorite', category: 'Pizza', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:20.95, description:'Housemade meatballs, pepperoni, Italian sausage, mushrooms, green bell peppers, black olives, white onions and seasoned tomatoes.')
MenuItem.create(item: 'Chicken Bacon Ranch', category: 'Pizza', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:20.95, description:'Grilled garlic chicken, smoked bacon, jack and cheddar cheese, red onions, diced tomatoes and a drizzle of ranch.')
MenuItem.create(item: 'Mediterranean', category: 'Pizza', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:20.95, description:'Grilled chicken breast, basil pesto, roasted garlic, Kalamata olives, sun-dried and seasoned tomatoes, feta cheese and sliced peperoncinis.')

MenuItem.create(item: 'BJs Brewhouse Burger', category: 'Handcrafted Burgers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:7.25, description:'A classic diner burger packed with flavor, featuring a fresh, never frozen 5 oz. beef patty. On a Parmesan crusted bun with grilled onions, lettuce, tomatoes and pickles.')
MenuItem.create(item: 'Black Bleu-House Burger', category: 'Handcrafted Burgers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:8.25, description:'With chipotle, bleu cheese crumbles, Applewood smoked bacon, roasted garlic aioli and tomatoes.')
MenuItem.create(item: 'Classic Burger', category: 'Handcrafted Burgers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:9.50, description:'With tomatoes, lettuce, pickles, mayonnaise and BJ’s signature burger sauce on a toasted bun.')
MenuItem.create(item: 'Crispy Jalapeno Burger', category: 'Handcrafted Burgers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:10.95, description:'Fried jalapeños, pepper jack cheese, chipotle mayonnaise, Baja sauce, red onions, tomatoes, lettuce and cilantro on a toasted bun.')
MenuItem.create(item: 'Bacon Cheeseburger', category: 'Handcrafted Burgers', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:10.50, description:'With Applewood smoked bacon, cheddar cheese, tomatoes, lettuce, pickles, mayonnaise and BJ’s signature burger sauce on a toasted bun.')

MenuItem.create(item: 'Angel Hair Classico', category: 'Pasta Favorites', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:8.95, description:'Toasted garlic oil, fresh broccoli, Parmesan cheese, sun-dried tomatoes and basil.')
MenuItem.create(item: 'Cajun Pasta', category: 'Pasta Favorites', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:12.50, description:'Blackened chicken breast, fire-roasted red bell peppers, red onions, fettuccini noodles and creamy tomato sauce.')
MenuItem.create(item: 'Tuscan Chicken Limone', category: 'Pasta Favorites', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:13.95, description:'Sauteed with garlic, artichoke hearts and sun-dried tomatoes in a lemon butter sauce. Served over angel hair pasta with fresh, steamed baby spinach.')
MenuItem.create(item: 'Shrimp Scampi Pasta', category: 'Pasta Favorites', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:16.25, description:'Sauteed shrimp and angel hair pasta in a light blend of olive oil, butter, garlic, lemon juice and Roma tomatoes.')

MenuItem.create(item: 'BJs Peanut Butter Smores', category: 'Desserts', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:6.95, description:'BJs twist on the classic smore! Peanut butter layered on a Ghirardelli® triple chocolate cookie with marshmallow fluff and marshmallows baked to a golden finish, then topped with vanilla bean ice cream. Available in regular size only.')
MenuItem.create(item: 'Peach and Pecan Cobbler', category: 'Desserts', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:6.50, description:'A southern-style cobbler with flavors of lemon zest and vanilla, baked in a golden brown cornmeal batter. Served warm and topped with vanilla bean ice cream and candied pecans.')
MenuItem.create(item: 'Pizookie Trio', category: 'Desserts', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:9.95, description:'Three mini Pizookies each served with a scoop of ice cream. Pick three from your choice of BJs selection of Pizookies.')
MenuItem.create(item: 'Salted Caramel Pizookie', category: 'Desserts', merchant: '69596c1485f9422ea1c52b1526a86dd7', price:6.95, description:'A little sweet and a little salty. Made with caramel cookie dough, almond toffee, pretzel bites and white and dark chocolate chips. Topped with vanilla bean ice cream, caramel sauce and a Ghirardelli SQUARES dark chocolate.')

MenuItem.create(item: 'Buffalo Wings', category: 'Signature Appetizers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:9.79, description:'Boneless or traditional. Served with celery and Bleu Cheese or Ranch dressing. Sauces: Tennessee BBQ, Garlic Parmesan, Buffalo or Scorching Hot.')
MenuItem.create(item: 'Mozzarella Sticks', category: 'Signature Appetizers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:7.29, description:'Golden mozzarella blended with Asiago, then topped with Parmesan and Romano cheeses. Served with marinara sauce.')
MenuItem.create(item: 'Loaded Potato Skins', category: 'Signature Appetizers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:7.99, description:'Melted cheddar topped with crispy applewood-smoked bacon. Served with green onion sour cream.')
MenuItem.create(item: 'Crispy Green Bean Fries', category: 'Signature Appetizers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:7.39, description:'Breaded and fried golden brown. Served with a Cucumber-Wasabi Ranch dip.')

MenuItem.create(item: 'Rib-Eye', category: 'From the Grill', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:17.99, description:'10 ounces of our most tender cut with generous marbling and succulent flavor. Served with two choice sides.')
MenuItem.create(item: 'Baby Back Ribs', category: 'From the Grill', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:18.99, description:'Slow-cooked baby back pork ribs basted in Tennessee BBQ sauce, then fire-grilled. Served with seasoned fries and ginger-lime slaw.')
MenuItem.create(item: 'Sirloin', category: 'From the Grill', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:16.19, description:'Top sirloin trimmed to deliver a classic American cut. Served with two choice sides.')
MenuItem.create(item: 'Hibachi Chicken Skewers', category: 'From the Grill', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:9.49, description:'Grilled all-natural chicken breast marinated in garlic-black pepper soy sauce with a miso glaze. Served with jasmine rice pilaf, fresh broccoli and grilled pita.')
MenuItem.create(item: 'Norwegian Salmon', category: 'From the Grill', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:18.99, description:'Topped with sautéed langostino lobster and cremini mushrooms in a roasted Alfredo sauce. Served with two choice sides.')

MenuItem.create(item: 'American Stacked Burger', category: 'Handcrafted Burgers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:11.89, description:'Melted sharp cheddar cheese, onion bacon jam and Asiago & Parmesan spread between two fresh burgers with Thousand Island dressing and peppered bacon.')
MenuItem.create(item: 'Philly Stacked Burger', category: 'Handcrafted Burgers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:11.89, description:'Braised shredded beef, mozzarella, Asiago & Parmesan, roasted cremini mushrooms, spicy giardiniera and green onion between two fresh burgers with Swiss cheese, horseradish spread, onion bacon jam and peppered bacon.')
MenuItem.create(item: 'Spicy Cheeseburger', category: 'Handcrafted Burgers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:10.79, description:'Regional craft beer-cheese sauce, freshly sliced jalapeños, breaded fried jalapeños, chipotle mayo, lettuce, tomato and house-made guacamole.')
MenuItem.create(item: 'Bleu Cheese Burger', category: 'Handcrafted Burgers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:11.89, description:'Melted bleu cheese, roasted cremini mushrooms, balsamic and green onions between two fresh burgers. Topped with bleu cheese crumbles, peppered bacon and roasted garlic rosemary aioli.')
MenuItem.create(item: 'Classic Cheeseburger', category: 'Handcrafted Burgers', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:8.69, description:'Classic fire-grilled burger topped with melted American cheese. ')

MenuItem.create(item: 'Chicken Caesar Salad', category: 'Salads', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:10.29, description:'Grilled balsamic-marinated all-natural chicken breast served over freshly chopped romaine tossed in a Caesar Vinaigrette with shaved Parmesan and tomatoes.')
MenuItem.create(item: 'Pecan Chicken Salad', category: 'Salads', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:11.69, description:'Warm, crispy pecan-crusted chicken breast served over mixed greens tossed in Balsamic Vinaigrette with dried cranberries, mandarin oranges, sweetened pecans and bleu cheese.')
MenuItem.create(item: 'Yucatan Chicken Salad', category: 'Salads', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:9.99, description:'Roasted pulled all-natural chicken breast over mixed greens tossed with avocado, mixed cheese, tomato, red onion, cilantro and tostadas. Drizzled with Avocado Vinaigrette and chipotle crema.')
MenuItem.create(item: 'Chicken Cobb Salad', category: 'Salads', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:8.89, description:'Grilled balsamic-marinated all-natural chicken breast served over freshly chopped romaine with sliced avocado, grape tomatoes, hard-boiled egg, applewood-smoked bacon and crumbled bleu cheese with your choice of dressing.')

MenuItem.create(item: 'Tennessee Whiskey Cake', category: 'Desserts', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:7.19, description:'Warm toffee cake topped with glazed pecans and vanilla ice cream. Served with butterscotch Jack Daniel\'s Whiskey sauce.')
MenuItem.create(item: 'Vanilla Bean Cheesecake', category: 'Desserts', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:6.49, description:'Made with real vanilla beans, layered with white chocolate mousse and baked in a graham cracker crust. Topped with white chocolate shavings.')
MenuItem.create(item: 'Salted Caramel Cake', category: 'Desserts', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:6.19, description:'Vanilla cake layered with vanilla bean pudding and caramel crunch drizzled with a salted caramel glaze. Served with vanilla ice cream.')
MenuItem.create(item: 'Oreo Madness', category: 'Desserts', merchant: '', price:6.49, description:'Hand-crumbled crust and premium Ghirardelli sauce will drive you crazy.')
MenuItem.create(item: 'Peanut Butter Pie', category: 'Desserts', merchant: '9f065ae88c2e40be80c0d604eda7e6e0', price:5.89, description:'Chocolate ganache layered with peanut butter mousse in a peanut butter graham cracker crust. Topped with whipped cream and a peanut butter cup.')